USE movies;

-- 1
SELECT s.NAME FROM MOVIESTAR AS s
WHERE (s.GENDER = 'F' AND s.NAME IN (SELECT p.NAME FROM MOVIEEXEC AS p 
									 WHERE p.NETWORTH > 10000000));

-- 2
SELECT s.NAME FROM MOVIESTAR AS s
WHERE s.NAME NOT IN (SELECT p.NAME FROM MOVIEEXEC AS p);

-- 3
SELECT m.TITLE FROM MOVIE AS m
WHERE m.LENGTH > (SELECT m2.TITLE FROM MOVIE AS m2 
				  WHERE m2.TITLE = 'Star Wars');

-- 4
SELECT p.NAME, m.TITLE FROM MOVIEEXEC AS p
JOIN MOVIE AS m
ON m.PRODUCERC# = p.CERT#
WHERE p.NETWORTH > (SELECT p1.NETWORTH FROM MOVIEEXEC AS p1
					WHERE p1.NAME = 'Merv Griffin');