USE ships;

-- 1
SELECT DISTINCT(c.COUNTRY) FROM CLASSES AS c
WHERE c.NUMGUNS = (SELECT TOP 1 c1.NUMGUNS FROM CLASSES AS c1
				   ORDER BY c1.NUMGUNS DESC);
				   
-- 2
SELECT DISTINCT(c.CLASS) FROM CLASSES AS c
JOIN SHIPS AS s
ON s.CLASS = c.CLASS
JOIN OUTCOMES AS o
ON o.SHIP = s.NAME
WHERE o.RESULT = 'sunk';

-- 3
SELECT s.NAME, s.CLASS FROM SHIPS AS s
JOIN CLASSES AS c
ON c.CLASS = s.CLASS
WHERE c.BORE = 16;

-- 4
SELECT b.NAME FROM BATTLES AS b
JOIN OUTCOMES AS o
ON o.BATTLE = b.NAME
JOIN SHIPS AS s
ON s.NAME = o.SHIP
JOIN CLASSES AS c
ON c.CLASS = s.CLASS
WHERE s.CLASS = 'Kongo';

-- 5
SELECT s.CLASS, s.NAME FROM SHIPS AS s
JOIN CLASSES AS c
ON c.CLASS = s.CLASS
WHERE c.NUMGUNS >= ALL (SELECT c1.NUMGUNS FROM CLASSES AS c1
					WHERE c1.BORE = c.BORE);