USE ships;

-- 1
INSERT INTO CLASSES(CLASS, TYPE, COUNTRY, NUMGUNS, BORE, DISPLACEMENT)
VALUES ('Nelson', 'bb', 'Gt.Britain', 9, 16, 34000);

INSERT INTO SHIPS(NAME, CLASS, LAUNCHED)
VALUES ('Nelson', 'Nelson', 1927),
	   ('Rodney', 'Nelson', 1927);

-- 2
DELETE FROM ships
WHERE NAME IN (SELECT SHIP FROM OUTCOMES
			   WHERE RESULT='sunk');

-- 3
UPDATE CLASSES
SET BORE=BORE*2.5,
	DISPLACEMENT=DISPLACEMENT*1.1;