USE movies;

-- 1
SELECT m.NAME FROM MOVIESTAR AS m
JOIN STARSIN AS s
ON s.STARNAME = m.NAME
WHERE (m.GENDER = 'M' AND s.MOVIETITLE = 'The Usual Suspects');

-- 2
SELECT s.STARNAME FROM STARSIN AS s
JOIN MOVIE AS m
ON m.TITLE = s.MOVIETITLE
WHERE (s.MOVIEYEAR = 1995 AND m.STUDIONAME = 'MGM');

-- 3
SELECT DISTINCT(p.NAME) FROM MOVIEEXEC AS p
JOIN MOVIE AS m
ON m.PRODUCERC# = p.CERT#
WHERE m.STUDIONAME = 'MGM';

-- 4
SELECT m.TITLE FROM MOVIE AS m
WHERE m.LENGTH > (SELECT m1.LENGTH FROM MOVIE AS m1
				  WHERE M1.TITLE = 'Star Wars');

-- 5
SELECT p.NAME FROM MOVIEEXEC AS p
WHERE p.NETWORTH > (SELECT p1.NETWORTH FROM MOVIEEXEC AS p1
					WHERE p1.NAME = 'Stephen Spielberg');


-- 6
SELECT m.TITLE FROM MOVIE AS m
JOIN MOVIEEXEC AS p
ON p.CERT# = m.PRODUCERC#
WHERE p.NETWORTH > (SELECT p1.NETWORTH FROM MOVIEEXEC AS p1
					WHERE p1.NAME = 'Stephen Spielberg');