USE ships;

-- 1
SELECT s.NAME FROM SHIPS AS s
JOIN CLASSES AS c
ON c.CLASS = s.CLASS
WHERE c.DISPLACEMENT > 50000;

-- 2
SELECT s.NAME, c.DISPLACEMENT, c.NUMGUNS FROM SHIPS AS s
JOIN CLASSES AS c
ON c.CLASS = s.CLASS
JOIN OUTCOMES AS o
ON o.SHIP = s.NAME
JOIN BATTLES AS b
ON b.NAME = o.BATTLE
WHERE b.NAME = 'Guadalcanal';

-- 3
SELECT DISTINCT(c1.COUNTRY) FROM CLASSES AS c1
JOIN CLASSES AS c2
ON c1.COUNTRY = c2.COUNTRY
WHERE c1.TYPE != c2.TYPE;

-- 4
SELECT o1.SHIP FROM OUTCOMES AS o1
JOIN BATTLES AS b1
ON b1.NAME = o1.BATTLE
JOIN OUTCOMES AS o2
ON o2.SHIP = o1.SHIP
JOIN BATTLES AS b2
ON b2.NAME = o2.BATTLE
WHERE (o1.RESULT = 'damaged' AND b2.DATE > b1.DATE);