USE movies;

-- 1
SELECT s.ADDRESS FROM STUDIO AS s
WHERE s.NAME = 'Disney';

-- 2
SELECT m.BIRTHDATE FROM MOVIESTAR AS m
WHERE m.NAME = 'Jack Nicholson';

-- 3
SELECT s.NAME FROM MOVIESTAR AS s
JOIN STARSIN AS si
ON si.STARNAME = s.NAME
WHERE (si.MOVIEYEAR = 1980 OR LOWER(si.MOVIETITLE) LIKE LOWER('%Knight%'));

-- 4
SELECT e.NAME FROM MOVIEEXEC AS e
WHERE e.NETWORTH > 10000000;

-- 5
SELECT * FROM MOVIESTAR AS s
WHERE s.GENDER = 'm' OR s.ADDRESS = 'Prefect Rd.';