USE ships;

-- 1
SELECT c.CLASS, c.COUNTRY FROM CLASSES AS c
WHERE c.NUMGUNS < 10;

-- 2
SELECT s.NAME AS 'shipName' FROM SHIPS AS s
WHERE s.LAUNCHED < 1918;

-- 3
SELECT o.SHIP, o.BATTLE FROM OUTCOMES AS o
WHERE o.RESULT = 'sunk';

-- 4
SELECT s.NAME FROM SHIPS AS s
WHERE s.NAME = s.CLASS;

-- 5
SELECT s.NAME FROM SHIPS AS s
WHERE s.NAME LIKE 'R%';

-- 6
SELECT s.NAME FROM SHIPS AS s
WHERE s.NAME LIKE '% %';