USE movies;

-- 1
SELECT TITLE, YEAR, LENGTH FROM MOVIE
WHERE (LENGTH IS NULL OR LENGTH > 120 AND YEAR < 2000);

-- 2
SELECT NAME, GENDER FROM MOVIESTAR
WHERE (NAME LIKE 'J%' AND BIRTHDATE > 1948)
ORDER BY NAME DESC;

-- 3
SELECT s.NAME, COUNT(DISTINCT si.STARNAME) FROM STUDIO AS s
JOIN MOVIE AS m
ON m.STUDIONAME = s.NAME
JOIN STARSIN AS si
ON si.MOVIETITLE = m.TITLE
GROUP BY s.NAME;

-- 4
SELECT STARNAME, COUNT(MOVIETITLE) FROM STARSIN
GROUP BY STARNAME;

-- 5
SELECT DISTINCT s.NAME, m.TITLE, m.YEAR FROM STUDIO AS s
JOIN MOVIE AS m
ON m.STUDIONAME = s.NAME
WHERE m.YEAR = (SELECT MAX(YEAR) FROM MOVIE
				WHERE STUDIONAME = s.NAME);

-- 6
SELECT TOP 1 NAME FROM MOVIESTAR
WHERE GENDER = 'M'
ORDER BY BIRTHDATE DESC;

-- 7
SELECT DISTINCT si.STARNAME, m.STUDIONAME FROM STARSIN AS si
JOIN MOVIE AS m
ON m.TITLE = si.MOVIETITLE
WHERE si.STARNAME = (SELECT TOP 1 si1.STARNAME FROM STARSIN AS si1
					 JOIN MOVIE AS m1
					 ON m1.TITLE = si1.MOVIETITLE
					 WHERE m1.STUDIONAME = m.STUDIONAME
					 GROUP BY si1.STARNAME, m1.STUDIONAME
					 ORDER BY COUNT(m1.TITLE) DESC);

-- 8
SELECT m.TITLE, m.YEAR, COUNT(si.STARNAME) AS 'actors count' FROM MOVIE AS m
JOIN STARSIN AS si
ON si.MOVIETITLE = m.TITLE
GROUP BY m.TITLE, m.YEAR
HAVING COUNT(si.STARNAME) > 2;