USE ships;

-- 1
SELECT DISTINCT s.NAME FROM SHIPS AS s
JOIN OUTCOMES AS o
ON o.SHIP = s.NAME
WHERE (s.NAME LIKE 'C%' OR s.NAME LIKE 'K%');

-- 2
SELECT DISTINCT s.NAME, c.COUNTRY FROM SHIPS AS s
JOIN CLASSES AS c
ON c.CLASS = s.CLASS
LEFT JOIN OUTCOMES AS o
ON o.SHIP = s.NAME
WHERE (o.RESULT IS NULL OR o.RESULT != 'sunk');

-- 3
SELECT c.COUNTRY, COUNT(o.SHIP) FROM CLASSES AS c
LEFT JOIN SHIPS AS s
ON s.CLASS = c.CLASS
LEFT JOIN OUTCOMES AS o
ON o.SHIP = s.NAME
WHERE (o.RESULT IS NULL OR o.RESULT = 'sunk')
GROUP BY c.COUNTRY;

-- 4
SELECT b.NAME FROM BATTLES AS b
JOIN OUTCOMES AS o
ON o.BATTLE = b.NAME
GROUP BY b.NAME
HAVING COUNT(o.SHIP) > (SELECT COUNT(o1.SHIP) FROM OUTCOMES AS o1
						WHERE o1.BATTLE = 'Guadalcanal');

-- 5
SELECT b.NAME FROM BATTLES AS b
JOIN OUTCOMES AS o
ON o.BATTLE = b.NAME
JOIN SHIPS AS s
ON s.NAME = o.SHIP
JOIN CLASSES AS c
ON c.CLASS = s.CLASS
GROUP BY b.NAME
HAVING COUNT(c.COUNTRY) > (SELECT COUNT(c1.COUNTRY) FROM OUTCOMES AS o1
							JOIN SHIPS AS s1
							ON s1.NAME = o1.SHIP
							JOIN CLASSES AS c1
							ON c1.CLASS = s1.CLASS
							WHERE o1.BATTLE = 'Surigao Strait');

-- 6
SELECT s.NAME FROM CLASSES AS c
JOIN SHIPS AS s
ON s.CLASS = c.CLASS
WHERE (c.DISPLACEMENT = (SELECT MIN(c1.DISPLACEMENT) FROM CLASSES AS c1)
	   AND c.NUMGUNS = (SELECT MAX(c1.NUMGUNS) FROM CLASSES AS c1
						WHERE c1.DISPLACEMENT = c.DISPLACEMENT));

-- 7
SELECT COUNT(DISTINCT o.SHIP) AS 'ships count' FROM OUTCOMES AS o
JOIN BATTLES AS b
ON b.NAME = o.BATTLE
WHERE (o.RESULT = 'damaged' AND EXISTS(SELECT * FROM OUTCOMES AS o1
									WHERE(o1.SHIP = o.SHIP AND o1.RESULT = 'ok')));

-- 8
SELECT o.SHIP FROM OUTCOMES AS o
JOIN BATTLES AS b
ON b.NAME = o.BATTLE
WHERE (o.RESULT = 'damaged' AND (SELECT COUNT(DISTINCT o1.SHIP) FROM OUTCOMES AS o1
								 WHERE o1.BATTLE = (SELECT o2.BATTLE FROM OUTCOMES AS o2
													WHERE(o2.SHIP = o.SHIP AND o2.RESULT = 'ok')))
								 >
								 (SELECT COUNT(o1.SHIP) FROM OUTCOMES AS o1
								  WHERE o1.BATTLE = o.BATTLE));