USE ships;

-- 1
SELECT s.NAME, s.CLASS, s.LAUNCHED, c.TYPE, c.COUNTRY, c.NUMGUNS, c.BORE, c.DISPLACEMENT FROM SHIPS AS s
LEFT JOIN CLASSES AS c
ON c.CLASS = s.CLASS;

-- 2
(SELECT s.NAME, s.CLASS, s.LAUNCHED, c.TYPE, c.COUNTRY, c.NUMGUNS, c.BORE, c.DISPLACEMENT FROM SHIPS AS s
LEFT JOIN CLASSES AS c
ON c.CLASS = s.CLASS)
UNION
(SELECT s.NAME, s.CLASS, s.LAUNCHED, c.TYPE, c.COUNTRY, c.NUMGUNS, c.BORE, c.DISPLACEMENT FROM SHIPS AS s
RIGHT JOIN CLASSES AS c
ON c.CLASS = s.CLASS
WHERE EXISTS (SELECT s1.NAME FROM SHIPS AS s1
			  WHERE s1.NAME = c.CLASS));

-- 3
SELECT c.COUNTRY, s.NAME FROM CLASSES AS c
JOIN SHIPS AS s
ON s.CLASS = c.CLASS
LEFT JOIN OUTCOMES AS o
ON o.SHIP = s.NAME
WHERE o.SHIP IS NULL;

-- 4
SELECT s.NAME AS 'Ship Name' FROM SHIPS AS s
JOIN CLASSES AS c
ON c.CLASS = s.CLASS
WHERE (c.NUMGUNS >= 7 AND s.LAUNCHED = 1916);

-- 5
SELECT o.SHIP, o.BATTLE, b.DATE FROM OUTCOMES AS o
JOIN BATTLES AS b
ON b.NAME = o.BATTLE
WHERE o.RESULT = 'sunk'
ORDER BY b.NAME;

-- 6
SELECT s.NAME, c.DISPLACEMENT, s.LAUNCHED FROM SHIPS AS s
JOIN CLASSES AS c
ON c.CLASS = s.CLASS
WHERE s.NAME = s.CLASS;

-- 7
SELECT c.CLASS FROM CLASSES AS c
LEFT JOIN SHIPS AS s
ON s.CLASS = c.CLASS
WHERE s.CLASS IS NULL;

-- 8
SELECT s.NAME, c.DISPLACEMENT, c.NUMGUNS, o.RESULT FROM CLASSES AS c
JOIN SHIPS AS s
ON s.CLASS = c.CLASS
JOIN OUTCOMES AS o
ON o.SHIP = s.NAME
WHERE o.BATTLE = 'North Atlantic';